### ISSUE TITLE
Is notdnethack to be updated in line with new dnethack features?

### ISSUE THREAD

**Issue by cosmodreamer** [demogorgon22/notdnethack-oldarchive#4]
E.g. androids, madmen, abilities menu (ctrl+b), etc... many patches and fixes? Or notdnethack is on its own way?

**Comment by demogorgon22** [comment]
Yes, currently a rewrite is in the works. https://github.com/demogorgon22/notdnethack2
If you want to pull it and play it locally be warned that it isn't feature complete yet and still missing a lot of general ndnh changes. Hoping to have it done some time in December to fit the theme of all other ndnh timings but that may be optimistic.
